// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: Background
			/// 2D
			/// </summary>
			public const string Background = "Background";

			/// <summary>
			/// Tag: Hellephant
			/// 2D
			/// </summary>
			public const string Hellephant = "Hellephant";

			/// <summary>
			/// Tag: Player
			/// 2D
			/// </summary>
			public const string Player = "Player";

			/// <summary>
			/// Tag: ZomBear
			/// 2D
			/// </summary>
			public const string ZomBear = "ZomBear";

			/// <summary>
			/// Tag: ZomBunny
			/// 2D
			/// </summary>
			public const string ZomBunny = "ZomBunny";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: HellephantVar
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string HellephantVar = "HellephantVar";

			/// <summary>
			/// Variable: PlayerVar
			/// Range: [0 - 2]
			/// Type: Global
			/// </summary>
			public const string PlayerVar = "PlayerVar";

			/// <summary>
			/// Variable: ZomBearVar
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string ZomBearVar = "ZomBearVar";

			/// <summary>
			/// Variable: ZomBunnyVar
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string ZomBunnyVar = "ZomBunnyVar";

		}

		public class Channels
		{
			public const string Effects = "Effects";

			public const string Master = "Master";

		}
	}
}
